# Generated by Django 5.2.7 on 2025-11-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='precio',
        ),
        migrations.AddField(
            model_name='book',
            name='precio_cop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (COP)'),
        ),
    ]
