# Generated by Django 5.2.7 on 2025-11-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de páginas'),
        ),
    ]
